services:
  # Container fürs Backend
  laravel:
    # Setze den Container namen
    container_name: ${APP_NAME}.00
    restart: unless-stopped
    # Baue den Container aus dem Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    # Setze die Datenbank Umgebungsvariablen
    env_file:
      - .env.docker
    depends_on:
      - db
    # Setze die Volumes für den Container.
    volumes:
      - ./database:/var/www/html/database
    # Leite den container port 80 auf den gegebenen Host port um
    ports:
      - ${EXPOSED_BACKEND_PORT:-8747}:80
  db:
    container_name: ${APP_NAME}.db
    restart: unless-stopped
    image: mariadb:11.5.2
    env_file:
      - .env.docker
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  admin:
    container_name: ${APP_NAME}.admin
    restart: unless-stopped
    image: adminer:4.8.1
    ports:
      - ${EXPOSED_ADMINER_PORT:-8748}:8080

  swagger:
    container_name: ${APP_NAME}.swagger
    restart: unless-stopped
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON_URL=/api/docs
      - BASE_URL=/docs
    ports:
      - ${EXPOSED_SWAGGER_PORT:-8749}:8080
